services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=learnpagination
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    expose:
      - "6000"
    ports:
      - "6000:6000"
    command: -p 6000
    volumes:
      - database:/data/postgres
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
  database:
