CREATE TABLE IF NOT EXISTS users (
  -- it is recommended to used GENERATED ALWAYS AS IDENTITY instead of SERIAL
  -- because SERIAL is an old implementation of postgres
  -- on the other hand, GAAI is SQL compliant
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  name VARCHAR(50) UNIQUE NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS posts (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  public_id UUID UNIQUE NOT NULL DEFAULT gen_random_uuid(),
  user_id INTEGER NOT NULL,
  text TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  FOREIGN KEY (user_id) REFERENCES users(id)
);

-- insertions
INSERT INTO users (name) VALUES
('Ana Clara'), ('Bruno Silva'), ('Carla Mendes'), ('Diego Rocha'), ('Eduarda Souza'),
('Felipe Martins'), ('Gabriela Ramos'), ('Henrique Castro'), ('Isabela Almeida'), ('João Pedro'),
('Kátia Nogueira'), ('Lucas Andrade'), ('Mariana Costa'), ('Nicolas Vieira'), ('Olívia Fernandes'),
('Paulo Henrique'), ('Queila Santos'), ('Rafael Lopes'), ('Sofia Teixeira'), ('Tiago Moura'),
('Ursula Carvalho'), ('Vinícius Pires'), ('Wagner Gomes'), ('Ximena Duarte'), ('Yuri Barros'),
('Zilda Correia'), ('Arthur Reis'), ('Beatriz Faria'), ('Caio Moreira'), ('Daniela Freitas'),
('Elisa Cardoso'), ('Fernando Brito'), ('Giovana Araújo'), ('Hugo Lima'), ('Ingrid Peixoto'),
('Júlio Cesar'), ('Larissa Monteiro'), ('Marcelo Braga'), ('Natália Fonseca'), ('Otávio Maciel'),
('Patrícia Morais'), ('Rodrigo Torres'), ('Simone Paiva'), ('Thiago Rios'), ('Vera Lucena'),
('William Assis'), ('Aline Duarte'), ('Bernardo Sales'), ('Camila Rocha'), ('Davi Silveira'),
('Estela Nunes'), ('Flávio Correia'), ('Helena Castro'), ('Igor Mendes'), ('Janaina Luz'),
('Kelly Araújo'), ('Leandro Figueiredo'), ('Marta Santana'), ('Noemi Dias'), ('Orlando Soares'),
('Priscila Moura'), ('Renato Guimarães'), ('Sara Barreto'), ('Tomás Vasconcelos'), ('Úrsula Prado'),
('Valentina Melo'), ('Wesley Duarte'), ('Xavier Mourão'), ('Yasmin Bastos'), ('Zeca Campos'),
('Adriana Alves'), ('Breno Oliveira'), ('Cristina Duarte'), ('Douglas Mendes'), ('Elaine Pinto'),
('Fabiano Freire'), ('Graziella Sampaio'), ('Heitor Silveira'), ('Ítalo Neves'), ('Joana Martins'),
('Kleber Tavares'), ('Luana Ramos'), ('Mateus Dias'), ('Nicole Pinheiro'), ('Otto Fernandes'),
('Paula Lima'), ('Raquel Brito'), ('Samuel Moreira'), ('Talita Nogueira'), ('Ulisses Matos'),
('Vitória Sales'), ('Wellington Araujo'), ('Xuxa Lacerda'), ('Yasmin Rocha'), ('Zion Carvalho');

INSERT INTO posts (user_id, text) VALUES
(1, 'Comecei a semana organizando a agenda; já me sinto mais leve.'),
(1, 'Café coado na hora e silêncio de manhã: perfeito.'),
(2, 'Voltei a correr no parque e consegui bater meu tempo.'),
(2, 'Alguém indica um tênis bom para pisada neutra?'),
(3, 'Dia chuvoso combina com livro e manta no sofá.'),
(3, 'Reorganizei a estante e achei um clássico que eu amo.'),
(4, 'Teste de receita nova: risoto de cogumelos aprovado.'),
(4, 'Próxima meta: aprender a fazer pão de fermentação natural.'),
(5, 'Peguei um pôr do sol incrível na volta para casa.'),
(5, 'Desliguei as notificações e a mente agradeceu.'),
(6, 'Terminei um projeto difícil no trabalho; orgulho define.'),
(6, 'Dica de foco: bloco de 25 minutos e pausa curta funciona.'),
(7, 'Meu gato decidiu que o teclado é cama; produtividade zero.'),
(7, 'Comprei uma planta e já virei pai de suculentas.'),
(8, 'Playlist de jazz salvou minha manhã.'),
(8, 'Aceito indicações de shows intimistas em SP.'),
(9, 'Arrisquei um curry hoje e ficou ótimo.'),
(9, 'Sábado é dia de feira e pastel de queijo.'),
(10, 'Finalmente comecei a série que todo mundo comenta.'),
(10, 'Dois episódios e já viciei; roteiro redondinho.'),
(11, 'Troquei o celular por um livro no ônibus; experiência melhor.'),
(11, 'Anotei ideias no papel e tudo fez mais sentido.'),
(12, 'Aula de natação rendendo; respiração controlada.'),
(12, 'Nada como água para zerar a cabeça.'),
(13, 'Faxina com música alta é terapia barata.'),
(13, 'Doei roupas e ganhei espaço no armário.'),
(14, 'Amanheci inspirada; escrevi duas páginas do meu conto.'),
(14, 'Procuro clube de escrita online para trocar textos.'),
(15, 'Café da tarde com bolo simples é meu ritual favorito.'),
(15, 'Aprendi a fazer calda brilhante sem erro.'),
(16, 'Futebol na praça e conversa boa depois do jogo.'),
(16, 'Voltei a treinar fundamentos; paciência é tudo.'),
(17, 'Passei no mercado e consegui manter a lista; vitória.'),
(17, 'Economia doméstica começa no carrinho, né?'),
(18, 'Reunião que poderia ser e-mail: todos já vivemos isso.'),
(18, 'Agenda enxuta = mais tempo para ler.'),
(19, 'Bolo de cenoura com cobertura de chocolate: sucesso total.'),
(19, 'Próximo teste será pudim sem furinhos.'),
(20, 'Trânsito pesado, podcast bom; deu para aprender bastante.'),
(20, 'Indiquem podcasts de história que valham a pena.'),
(21, 'Domingo de churrasco com família; risadas infinitas.'),
(21, 'Levei farofa de banana e acabou primeiro.'),
(22, 'Pão caseiro saiu do forno perfumando a casa.'),
(22, 'Ajustei hidratação da massa e melhorou demais.'),
(23, 'Voltei ao violão e os dedos já estão doendo.'),
(23, 'Reaprendi dois acordes que tinha esquecido.'),
(24, 'Dia de organizar finanças e metas do mês.'),
(24, 'Planilha pronta; agora é seguir o plano.'),
(25, 'Teste de maquiagem leve para o dia a dia; gostei do resultado.'),
(25, 'Filtro solar virou item número um da bolsa.'),
(26, 'Primeiras fotos em RAW e já percebi a diferença.'),
(26, 'Fotometria ainda confunde, mas estou pegando o jeito.'),
(27, 'Terminei aquele romance que enrolei por meses.'),
(27, 'Vou alternar ficção e ensaio para variar o ritmo.'),
(28, 'Convidei amigos para um jogo de tabuleiro à noite.'),
(28, 'Nada como risada boa para fechar o dia.'),
(29, 'Recomecei na corrida com ritmo leve; sem pressa.'),
(29, 'Alongamento antes e depois fez toda a diferença.'),
(30, 'Lasanha no almoço de família; disputaram o último pedaço.'),
(30, 'Anotei a receita para repetir no próximo domingo.'),
(31, 'Experimentei ficar uma hora offline; paz imediata.'),
(31, 'Silenciar grupos foi libertador.'),
(32, 'Fui ao estádio e vibrei como criança.'),
(32, 'Time ganhou e a volta pra casa ficou mais leve.'),
(33, 'Troquei as cores do quarto e parece outro espaço.'),
(33, 'Iluminação quente deixou tudo aconchegante.'),
(34, 'Passei na entrevista; começo mês que vem.'),
(34, 'Ansioso, mas com vontade de aprender tudo.'),
(35, 'Receita vegana de grão-de-bico surpreendeu.'),
(35, 'Descobri temperos novos e já viciei.'),
(36, 'Zerei um jogo antigo que nunca terminei.'),
(36, 'Modo história bem amarrado; valeu a maratona.'),
(37, 'Comprei duas plantas novas e dei nome pra elas.'),
(37, 'Regar sem afogar: missão diária.'),
(38, 'Pesquei com meu pai e voltei com boas histórias.'),
(38, 'O silêncio da represa é uma aula de paciência.'),
(39, 'Primeira aula de dança: vergonha passou no minuto dois.'),
(39, 'Descobri que tenho ritmo sim; faltava coragem.'),
(40, 'Maratona de filmes clássicos na lista.'),
(40, 'Hoje foi dia de Hitchcock; fotografia impecável.'),
(41, 'Bolo com as crianças virou bagunça boa.'),
(41, 'Farinha pela cozinha toda, mas valeu a memória.'),
(42, 'Bicicleta nova, rota nova, humor novo.'),
(42, 'Capacete e luzes em dia; segurança primeiro.'),
(43, 'Organizei a casa e achei coisas que nem lembrava.'),
(43, 'Destralhar ajuda a pensar melhor.'),
(44, 'Aniversário com amigos de infância; tempo voa.'),
(44, 'Agradecido por cada mensagem recebida.'),
(45, 'Visitei minha mãe e saí com potes na sacola.'),
(45, 'Afeto também se guarda em Tupperware.'),
(46, 'Resolvi um bug que me perseguiu a semana inteira.'),
(46, 'Testes passando; agora dá até para dormir.'),
(47, 'Terminei um quadro pequeno e adorei as cores.'),
(47, 'Próximo passo: aprender técnica de luz e sombra.'),
(48, 'Lua cheia linda; tentei fotografar com tripé.'),
(48, 'Aprendi que ISO alto nem sempre é amigo.'),
(49, 'Comecei série espanhola; sotaque delicioso.'),
(49, 'Roteiro esperto e episódios curtos; perfeito pra noite.'),
(50, 'Pedalei cedo e a cidade estava silenciosa.'),
(50, 'Subida longa, mas a vista compensou.'),
(51, 'Adotei um gatinho hoje; já dominou o sofá.'),
(52, 'Acordes novos no violão; dedos calejados e felizes.'),
(53, 'Yoga ao nascer do sol; respiração guiou tudo.'),
(54, 'Corrida na chuva: libertadora e refrescante.'),
(55, 'Preparei surpresa simples para uma amiga; sorriso garantido.'),
(56, 'Sessão de comédia romântica para relaxar a cabeça.'),
(57, 'Basquete com os primos; muita risada e arremesso torto.'),
(58, 'Bolo de chocolate saiu perfeito; textura dos sonhos.'),
(59, 'Romance policial prendendo do começo ao fim.'),
(60, 'Pesca com amigos e papo sem pressa.'),
(61, 'Mala quase pronta; contagem regressiva para a viagem.'),
(62, 'Assisti à final do campeonato; coração na boca.'),
(63, 'Primeiras fotos de rua; luz da tarde ajuda muito.'),
(64, 'Treino de natação concluído; foco na técnica.'),
(65, 'Testei maquiagem nova e gostei do acabamento.'),
(66, 'Estudo de piano avançando uma peça por semana.'),
(67, 'Campanha de RPG voltou; personagens em apuros.'),
(68, 'Passeio no parque para arejar as ideias.'),
(69, 'Brigadeiro na colher e conversa na varanda.'),
(70, 'Coloquei um vinil antigo pra tocar; nostalgia pura.'),
(71, 'Comecei o dia na academia e rendeu bem.'),
(72, 'Aprendendo inglês com filmes e legendas em inglês.'),
(73, 'Pontos de bordado finalmente saíram bonitos.'),
(74, 'Jogo de futebol tenso, mas valeu cada minuto.'),
(75, 'Jardinagem em vasos: primeira flor do ano abriu.'),
(76, 'Primeiro rolê de patins na orla; adrenalina boa.'),
(77, 'Passeio de fim de tarde com a pequena; momento nosso.'),
(78, 'Cartas com amigos e histórias antigas na mesa.'),
(79, 'Podcast de história durante a faxina; melhor combo.'),
(80, 'Estudando biologia e fascinada com ecossistemas.'),
(81, 'Lavei o carro e já caiu uma chuva; clássico.'),
(82, 'Domingo de autocuidado: unhas feitas e série leve.'),
(83, 'Musculação com técnica nova; menos peso, mais controle.'),
(84, 'Cookies saíram do forno cheirando a infância.'),
(85, 'Primeiras notas no violino; paciência será essencial.'),
(86, 'Caminhada longa e cabeça mais leve.'),
(87, 'Fotografei o pôr do sol e acertei a exposição.'),
(88, 'Joguei truco e defendi uma queda épica.'),
(89, 'Jantar especial de quinta: massa fresca feita em casa.'),
(90, 'Leitura de filosofia antes de dormir; mente em calma.'),
(91, 'Ensaios para a peça avançando; elenco afinado.'),
(92, 'Cuidei do jardim e replantei duas mudas.'),
(93, 'Redescobri músicas dos anos 80 e dancei na sala.'),
(94, 'Testei um delineado diferente e ficou ótimo.'),
(95, 'Documentário de ciência abriu mil perguntas novas.'),
(96, 'Comprei flores no mercado e a sala ganhou vida.'),
(97, 'Caminhada cedo para aproveitar o ar frio da manhã.'),
(98, 'Cinema com amigos: risadas e boa companhia.'),
(99, 'Churrasco no quintal e playlist caprichada.'),
(100, 'Organizei os livros por tema; ficou mais fácil de achar.');
